In [14]:
import sys,os
import mxnet as mx
# sys.path

In [17]:
# array creation
a = mx.nd.array([1,2,3])
b = mx.nd.array([[1,2,3],[4,5,6]])
{'a.shape':a.shape,'b.shape':b.shape,'b_shape_0':b.shape[0],'b_shape_1':b.shape[1]}
# {'a.shape_0':a.shape[0]}

{'a.shape': (3L,), 'b.shape': (2L, 3L), 'b_shape_0': 2L, 'b_shape_1': 3L}

In [20]:
import numpy as np
import math
c = np.arange(15).reshape(3,5)
# create a 2-dimensinal array from a numpy.ndarray object
a =mx.nd.array(c)
print a
{'a.shape':a.shape}

<NDArray 3x5 @cpu(0)>


{'a.shape': (3L, 5L)}

In [28]:
# float32 is used in deafult 
a = mx.nd.array([1,2,3])
# create a int array
b = mx.nd.array([1,2,3],dtype=np.int32)
# create a 16-bit float array
c = mx.nd.array([1,2,3],dtype=np.float16)
# {'a.shape':a.shape,'b.shape':b.shape,'c.shape':c.shape}
{'a.dtype':a.dtype,'b.dtype':b.dtype,'c.dtype':c.dtype}

{'a.dtype': numpy.float32, 'b.dtype': numpy.int32, 'c.dtype': numpy.float16}

In [29]:
# create zeros; 
a = mx.nd.zeros((2,3))
# create ones; 
b = mx.nd.ones((2,3))
# create full element with 7
c = mx.nd.full((2,3),7)
# create initial content is random , which depands on the memory state 
d = mx.nd.empty((2,3))

In [33]:
#convert NDArray to numpy.ndarray by function asnumpy for printing
b = mx.nd.ones((2,3))
b.asnumpy()

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32)

In [43]:
a = mx.nd.ones((2,3))
b = mx.nd.ones((2,3))
# elementwise plus
c = a + b
# elementwise minus
d = -c
# elementwise power and sin, and then transpose
e = mx.nd.sin(c**2).T
# elementwise max
f = mx.nd.maximum(a,c)
print e.asnumpy()


[[-0.7568025 -0.7568025]
 [-0.7568025 -0.7568025]
 [-0.7568025 -0.7568025]]


In [50]:
# * is for elemmentwise multiply, matrix-matrix multiplication is by dot
a = mx.nd.ones((2,3))
b = a*a 
print 'b = ', b.asnumpy()
c = mx.nd.dot(a.T,a)
print 'c = ',c.asnumpy()

{'b':b.asnumpy(),'c':c.asnumpy()}

b =  [[ 1.  1.  1.]
 [ 1.  1.  1.]]
c =  [[ 2.  2.  2.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]]


{'b': array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=float32), 'c': array([[ 2.,  2.,  2.],
        [ 2.,  2.,  2.],
        [ 2.,  2.,  2.]], dtype=float32)}

In [65]:
# Index and Slicing
# [] applies on axis 0
a = mx.nd.array(np.arange(6).reshape(3,2))
print a.asnumpy()
a[0:2] = 1
print a.asnumpy()
# use slice_axis

d = mx.nd.slice_axis(a,axis=1,begin=1,end=2)
d.asnumpy()

[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]]
[[ 1.  1.]
 [ 1.  1.]
 [ 4.  5.]]


array([[ 1.],
       [ 1.],
       [ 5.]], dtype=float32)

In [68]:
a = mx.nd.array(np.arange(24))
print 'a = ',a.asnumpy()
b = a.reshape((2,3,4))
print 'b = ',b.asnumpy()


a =  [  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.]
b =  [[[  0.   1.   2.   3.]
  [  4.   5.   6.   7.]
  [  8.   9.  10.  11.]]

 [[ 12.  13.  14.  15.]
  [ 16.  17.  18.  19.]
  [ 20.  21.  22.  23.]]]


In [71]:
# reduce 
a = mx.nd.ones((2,3))
b = mx.nd.sum(a)
print 'a = ',a.asnumpy()
print 'b = ',b.asnumpy()

a =  [[ 1.  1.  1.]
 [ 1.  1.  1.]]
b =  [ 6.]


In [73]:
c = mx.nd.sum(a,axis = 0)
d = mx.nd.sum(a,axis = 1)

print 'c = ',c.asnumpy()
print 'd = ',d.asnumpy()

c =  [ 2.  2.  2.]
d =  [ 3.  3.]


In [76]:
#broadcast 
a = mx.nd.array(np.arange(6).reshape(6,1))
print 'a = ',a.asnumpy()
b = a.broadcast_to((6,2))
print 'b = ',b.asnumpy()

c = a.reshape((2,1,1,3))
print 'c = ',c.asnumpy()

d = c.broadcast_to((2,2,2,3))
print 'd = ',d.asnumpy()

a =  [[ 0.]
 [ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]]
b =  [[ 0.  0.]
 [ 1.  1.]
 [ 2.  2.]
 [ 3.  3.]
 [ 4.  4.]
 [ 5.  5.]]
c =  [[[[ 0.  1.  2.]]]


 [[[ 3.  4.  5.]]]]
d =  [[[[ 0.  1.  2.]
   [ 0.  1.  2.]]

  [[ 0.  1.  2.]
   [ 0.  1.  2.]]]


 [[[ 3.  4.  5.]
   [ 3.  4.  5.]]

  [[ 3.  4.  5.]
   [ 3.  4.  5.]]]]


In [89]:
#broadcast can be applied by * and + 
a = mx.nd.ones((3,2))
b = mx.nd.ones((1,2))
c = a + b
print 'c= ', c.asnumpy()
print b[0:1]

c=  [[ 2.  2.]
 [ 2.  2.]
 [ 2.  2.]]
<NDArray 1x2 @cpu(0)>


In [104]:
# copy and reference
a = mx.nd.ones((2,2))
b = a 
if (b is a):
    print " b is the same reference.."

# copy() is a deep copy method
b2 = a.copy()
if (b2 is a):
    print " b2 is the same reference.."
    

 b is the same reference..


In [109]:
b = mx.nd.ones(a.shape)
c = b
c[:]  = mx.nd.zeros(b.shape)
print (c is b)
print {'b':b.asnumpy(),'c':b.asnumpy()}

True
{'c': array([[ 0.,  0.],
       [ 0.,  0.]], dtype=float32), 'b': array([[ 0.,  0.],
       [ 0.,  0.]], dtype=float32)}


#### Serialize From/To (Distributed) Filesystem
There are two ways to save/load data from disks. First is to use **pickle**

In [112]:
import pickle as pkl 
a = mx.nd.ones((2,3))
# pack and then dump into disk
data = pkl.dumps(a)
pkl.dump(data,open('tmp.pickle','wb'))
# load from disk and then unpack
data = pkl.load(open('tmp.pickle','rb'))
b = pkl.loads(data)
b.asnumpy()

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32)

Second is to use **save** and **load** method, we can even save *list* and *dict*

In [116]:
a = mx.nd.ones((2,3))
b = mx.nd.ones((5,6))
mx.nd.save('temp.ndarray',[a,b])
c = mx.nd.load('temp.ndarray')
print 'c = ',c

c =  [<NDArray 2x3 @cpu(0)>, <NDArray 5x6 @cpu(0)>]
